# EXAMPLE 5: Create Releases
# This workflow creates GitHub releases when you push tags

name: Release Workflow

on:
  # Trigger when pushing version tags
  push:
    tags:
      - 'v*.*.*'  # Matches v1.0.0, v2.1.3, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to create releases
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all history for changelog
      
      # Generate changelog from commits
      - name: Generate changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      # Create the release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/$(git describe --tags --abbrev=0 HEAD^)...${{ github.ref_name }}
          draft: false
          prerelease: false
  
  # Build and upload artifacts
  build-artifacts:
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Build project
        run: |
          npm ci
          npm run build --if-present
          # Create a zip of your dist folder (if you have one)
          # zip -r dist.zip dist/
      
      # Upload artifacts to the release
      - name: Upload Release Asset
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.ref_name }}
          path: |
            dist/
            *.md
            package.json